name: terraform aws oidc workflow
on:
  push:
    branches:
      - qa
  pull_request:
    branches:
      - qa

jobs:
  qa-deploy:
    uses: ./.github/workflows/reusable-terraform-workflow.yml
    permissions:
      id-token: write
      contents: read
    with:
      region: "us-west-2"
    secrets:
      role: ${{ secrets.AWS_ROLE_QA }}