name: terraform aws oidc workflow
on:
  push:
    branches:
      - prod
  pull_request:
    branches:
      - prod

jobs:
  prod-deploy:
    uses: ./.github/workflows/reusable-terraform-workflow.yml
    with:
      environment: prod
      region: "us-west-2"
