name: terraform aws oidc workflow
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  dev-deploy:
    uses: ./.github/workflows/reusable-terraform-workflow.yml
    with:
      environment: dev
      region: "us-west-2"