name: terraform aws oidc workflow
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  dev-deploy:
    uses: ./.github/workflows/reusable-terraform-workflow.yml
    permissions:
      id-token: write
      contents: read
    with:
      region: "us-west-2"
    secrets:
      role: ${{ secrets.AWS_ROLE_DEV }}